export const browserCoreExamples = [
  "omniclaw browser status",
  "omniclaw browser start",
  "omniclaw browser stop",
  "omniclaw browser tabs",
  "omniclaw browser open https://example.com",
  "omniclaw browser focus abcd1234",
  "omniclaw browser close abcd1234",
  "omniclaw browser screenshot",
  "omniclaw browser screenshot --full-page",
  "omniclaw browser screenshot --ref 12",
  "omniclaw browser snapshot",
  "omniclaw browser snapshot --format aria --limit 200",
  "omniclaw browser snapshot --efficient",
  "omniclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "omniclaw browser navigate https://example.com",
  "omniclaw browser resize 1280 720",
  "omniclaw browser click 12 --double",
  'omniclaw browser type 23 "hello" --submit',
  "omniclaw browser press Enter",
  "omniclaw browser hover 44",
  "omniclaw browser drag 10 11",
  "omniclaw browser select 9 OptionA OptionB",
  "omniclaw browser upload /tmp/file.pdf",
  'omniclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "omniclaw browser dialog --accept",
  'omniclaw browser wait --text "Done"',
  "omniclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "omniclaw browser console --level error",
  "omniclaw browser pdf",
];
